### PR TITLE
[Feature] Added proxyReqOverride option

### PR DESCRIPTION
**Pull request by minho-comcom-ai**
Added proxyReqOverride option for overriding the original `proxyReq` proxy event.

### CODE REVIEW

**Comment by stegano** [comment]
Hi, @minho-comcom-ai 
Could you please explain in which cases this feature is needed?

**Comment by minho-comcom-ai** [comment]
Hello, @stegano!
The purpose of this PR is to add headers (such as tracing) dynamically on each requests by following [this http-proxy document](https://www.npmjs.com/package/http-proxy#setup-a-stand-alone-proxy-server-with-proxy-request-header-re-writing).
There are `headers` option already in `http-proxy`, but it was globally affected to the same headers on every requests, not each requests.

**Comment by stegano** [comment]
@minho-comcom-ai 
Thanks for the explanation.

Adding header information dynamically to each request can be solved without modifying this library.

```ts
export default (req: NextApiRequest, res: NextApiResponse) => {
  if (req.url === '/api/test') {
    // Adding request headers dynamically
    req.headers['your-proxy-header'] = 'test';
  }
  nextHttpProxyMiddleware(req, res, {
    target: 'http://127.0.0.1:8099',
    pathRewrite: {
      '^/api': '',
    },
  });
};
```

And if you use the 'proxyReqOverride' you suggested, you won't be able to deal with the problem in #3.
Please let me know if I'm wrong. 
Thank you 😀

**Comment by stegano** [comment]
Close the issue. Please reopen if necessary.

**Pull request closed without merging**
