### PR TITLE
fix: make jest and ts-jest devDependencies

### PR DESCRIPTION
**Pull request by gthb**
Testing libraries should not be runtime dependencies.

### CODE REVIEW

**Comment by stegano** [comment]
Hi, @gthb

Thanks for your PR! 😀

I think all dependencies can move to devDependencies. 🤔

**Comment by gthb** [comment]
> I think all dependencies can move to devDependencies. 🤔

Oh! Sure, I guess 😊 — I only looked at the ones that were leading to version constraint conflicts in _our_ runtime dependencies.

**Comment by stegano** [comment]
@all-contributors please add @gtnb for code and ideas

**Comment by stegano** [comment]
@all-contributors please add @gthb for code and ideas

**Pull request merged**
