### PR TITLE
Use request scoped event emitter

### PR DESCRIPTION
**Pull request by Turee**
We had a problem when multiple concurrent requests were sent using the proxy, all got the same response. This fixed it for us.

### CODE REVIEW

**Comment by stegano** [comment]
Hi @Turee
Thanks for your reporting.
Is there any way to reproduce this issue?

I tried to test this issue, but I can't reproduce it.

Below is how I tested it.
1) Create a server that responds to random data using express
```ts
app.all('*', (req, res) => {
  const random = (Math.random() * 10000).toString(32);
  setTimeout(() => {
    res.status(200).json({ result: random });
  }, 10);
});
```
2) Proxy (1) in your nextjs app
```ts
export default (req: NextApiRequest, res: NextApiResponse) => (
  nextHttpProxyMiddleware(req, res, {
    target: 'http://localhost:9000',
    pathRewrite: {
      '^/api/test': '/',
    },
  })
);
```
3) Count by sending more than 100 requests simultaneously from the browser and storing the random data passed in the response
```ts
const responses = {};
(async () => {
  Array(100).fill(undefined).forEach(async () => {
    response = await axios('http://localhost:3002/api/test');
    const name = response.data.result;
    if (responses[name] === undefined) {
      responses[name] = 0;
    }
    responses[name] += 1;
  });
})();
```
4) There is no duplicate result of random data delivered as a response
```ts
Object.entries(responses).filter(([k, v]) => v === 2) // result: "[]"
```
Thanks :)

**Comment by Turee** [comment]
Hi @stegano thanks for replying. 

You need atleast two instances of the middleware for reproducing this issue and you need set some event handlers to the proxy object. Proxy object returned by the .createProxy() is an event emitter and if the object is shared by multiple instances of next-http-proxy-middleware the event handlers will clash.

**Comment by stegano** [comment]
Hi @Turee 

Does it mean that the meaning of at least two instances is the same as in the code example below?
```ts
export default (req: NextApiRequest, res: NextApiResponse) => (
   nextHttpProxyMiddleware(req, res, {
     target: 'http://localhost:9000',
     pathRewrite: {
       '^/api/test/1': '/',
       '^/api/test'/2/: '/',
     },
   })
);
```
Can you give me some code that can be reproduced?

**Comment by stegano** [comment]
Close the issue. Please reopen if necessary.

**Pull request closed without merging**
